version: "3.8"

services:
  app:
    build: .
    container_name: error_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "app.js"]
    networks:
      - error_network

networks:
  error_network:
    driver: bridge
